name: fordeal
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section,   # To add assets to your application, add an assets section, like this:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/mainIcon.png"



  assets:
    - assets/
    - assets/testJson/
    - assets/images/
    - assets/images/account/
    - assets/images/public/
    - assets/images/errors/
    - assets/images/product_details/
    - assets/images/account/my_orders/
    - assets/icons/
    - assets/images/json/



  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
